---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rflqetyb/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp 404.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .nojekyll $DEPLOYPATH
    - /bin/cp favicon.png $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp asset-manifest.json $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
