export const userlisadata = [
  {
    id: 1,
    img: "assets/img/profiles/avator1.jpg",
    username: "Store Administrator",
    phone: "+1 (555) 019-2831",
    email: "admin@futureprocessing.com",
    role: "Super Admin",
    createdon: "12 Jan 2026",
    status: "Active",
  },
  {
    id: 2,
    img: "assets/img/users/user-15.jpg",
    username: "Cashier Station #1",
    phone: "+1 (555) 014-9922",
    email: "cashier@futureprocessing.com",
    role: "POS Cashier",
    createdon: "15 Jan 2026",
    status: "Active",
  },
  {
    id: 3,
    img: "assets/img/users/user-16.jpg",
    username: "Omar Farooq",
    phone: "+1 (555) 017-8492",
    email: "omar@futureprocessing.com",
    role: "POS Cashier",
    createdon: "18 Jan 2026",
    status: "Active",
  },
  {
    id: 4,
    img: "assets/img/users/user-17.jpg",
    username: "Rose Miller",
    phone: "+1 (555) 013-6752",
    email: "rose@futureprocessing.com",
    role: "Store Manager",
    createdon: "23 Jan 2026",
    status: "Active",
  },
  {
    id: 5,
    img: "assets/img/users/user-18.jpg",
    username: "Kaitlin Ross",
    phone: "+1 (555) 018-5130",
    email: "kaitlin@futureprocessing.com",
    role: "Forecourt Attendant",
    createdon: "18 Feb 2026",
    status: "Active",
  },
];